### ISSUE TITLE
Error when untar the encrypted dataset

### ISSUE THREAD

**Issue by ZihanLiao** [wenet-e2e/WenetSpeech#32]
After downloading the whole dataset, an error occurs when doing the function `process_downloaded_object`. 
This seems to occur when untar the encrypted dataset.
![屏幕快照 2022-02-21 上午11 46 48](https://user-images.githubusercontent.com/54339989/154886025-82c41baa-cd32-4cca-82e3-569e98bcf744.png)

**Comment by SoonSYJ** [comment]
Hi,
How did you solve this?

**Comment by OUC-lan** [comment]
您好，我也发现了类似的问题，想请教下如何解决？

**Comment by Jack-du-ubc** [comment]
I got the same issue. Is there anyway to solve it?

**Comment by Jack-du-ubc** [comment]
@OUC-lan 如果之前是默认下载，可以安装ModelScope重新尝试
