### ISSUE TITLE
The mismatch between the marked duration and the actual audio duration.

### ISSUE THREAD

**Issue by luomingshuang** [wenet-e2e/WenetSpeech#33]
I am using k2 and Lhotse for wenetspeech ASR experiments. But there is an error happened. The error shows as follows:
![image](https://user-images.githubusercontent.com/37799481/160361158-a8c25f12-ee05-43be-9dc4-e668ea8330b9.png)

And then I check the actual duration for this sample (its marked duration is 786.44s):
<img width="426" alt="5305fba8604afa0e9cbb3a3ede5903f" src="https://user-images.githubusercontent.com/37799481/160361400-6ad396ff-cfce-4139-a8a6-1971fd86e7ca.png">

I find the marked duration is 988.89s.
<img width="428" alt="6675f17edaacbd75ec52064adb7de80" src="https://user-images.githubusercontent.com/37799481/160361653-66b7cf6d-655d-48b0-8441-ce905e253dcb.png">

So can we change the marked duration in the original marked transcripts? Or I should filter it with a filtering function to avoid this error?

**Comment by robin1001** [comment]
I'm not familiar with K2.  I think you can get the real duraiton by the audio if there is a mismatch.

**Comment by luomingshuang** [comment]
Thanks.


---Original---
From: &quot;Binbin ***@***.***&gt;
Date: Thu, Apr 14, 2022 11:57 AM
To: ***@***.***&gt;;
Cc: &quot;Mingshuang ***@***.******@***.***&gt;;
Subject: Re: [wenet-e2e/WenetSpeech] The mismatch between the marked durationand the actual audio duration. (Issue #33)




 
I'm not familiar with K2.  I think you can get the real duraiton by the audio if there is a mismatch.
 
&mdash;
