### ISSUE TITLE
下载数据集失败

### ISSUE THREAD

**Issue by bird7code** [wenet-e2e/WenetSpeech#34]
你好，执行邮件中的第三条命令时出现404的错误
![image](https://user-images.githubusercontent.com/93416649/163309944-791c1d7a-0c24-4f99-9d5f-55074fd7a754.png)
请问该如何解决

**Comment by robin1001** [comment]
检查一下你的网络，其他人没这个问题。

**Comment by bird7code** [comment]
> 检查一下你的网络，其他人没这个问题。

好的，谢谢
