### ISSUE TITLE
[Question] about the results

### ISSUE THREAD

**Issue by maxwellzh** [wenet-e2e/WenetSpeech#36]
Hi wenet team, thanks for this open dataset. I have some questions about the results in https://github.com/wenet-e2e/WenetSpeech/blob/main/README.md#benchmark

1. The espnet model is trained for 50 epochs, while wenet model only trained for half of that (26 epochs), why not both trained for the same iteration number?
2. The espnet model use an external Transformer LM in decoding, does wenet have the result decoding with an external LM?

**Comment by robin1001** [comment]
1. We do not have the resource to train 50 epochs at that time.
2. Transformer LM is not supported in WeNet. n-gram is supported, However, we didn't do the benchmark.
