### ISSUE TITLE
CC-BY-NC vs CC-BY

### ISSUE THREAD

**Issue by tshmak** [wenet-e2e/WenetSpeech#41]
I think if you want your data to be non-commercial, the license should be CC-BY-NC (https://creativecommons.org/licenses/by-nc/4.0/) rather than CC-BY (https://creativecommons.org/licenses/by/4.0/).

**Comment by robin1001** [comment]
Thank you very much. Currently we just describe it is non-commercial, but we hope it can be used for commercial in the future, so we use CC-BY.
