### ISSUE TITLE
The unlabeled data open source?

### ISSUE THREAD

**Issue by rookie0607** [wenet-e2e/WenetSpeech#44]
Thank you very much for your work, which has brought me many conveniences. It seems that the download method you provide can only download 10000 hours of labeled data. Is the unlabeled data open source?

**Comment by robin1001** [comment]
Yes, the unlabeled data is aslo given in the data. However, we only gives the labeled segments in the meta file.

**Comment by robin1001** [comment]
You can extract the unlabeled data according to the labeled time stamp.
