### ISSUE TITLE
下载之后解压失败

### ISSUE THREAD

**Issue by haha010508** [wenet-e2e/WenetSpeech#55]
请问这是这么回事？

utils/download_wenetspeech.sh: Processing /media/byd/disk3/WenetSpeech/DOWNLOAD_DIR/WenetSpeech.json.aes.tgz

gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
error writing output file

**Comment by haha010508** [comment]
复现方法：第一步：将密码存入文件；第二步：将v1.list 改成1行，就死只下载一个文件，然后运行shell脚本，注意不是modelscope方式，下载完成后，解压就报上述错误。

**Comment by LvHang** [comment]
已尝试复现，但并不存在问题，可正常下载。
建议仔细对照申请时官方邮件使用，检查是否存在密码错误等问题。

**Comment by haha010508** [comment]
经核查是密码错误导致，注：密码错误不影响下载，但是影响解压。

**Comment by SaintE419** [comment]
> 经核查是密码错误导致，注：密码错误不影响下载，但是影响解压。

我也遇到了这个问题，请问怎么解决的

**Comment by robin1001** [comment]
在申请页面中申请密码，见 
 https://docs.google.com/forms/d/e/1FAIpQLScjE1nzpvGvFYiwULs1zcffg6VadMDlyPP3OZi3cmd7Aijueg/viewform?usp=sf_link

**Comment by SaintE419** [comment]
> 在申请页面中申请密码，见 https://docs.google.com/forms/d/e/1FAIpQLScjE1nzpvGvFYiwULs1zcffg6VadMDlyPP3OZi3cmd7Aijueg/viewform?usp=sf_link

为什么觉得是密码问题？密码已申请并存入SAFEBOX，
